on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
     - name: INSTALL .NET CORE       
       run: dotnet --list

    # steps: 
    #  - name: BUILD WEBAPI
    #    run: dotnet build

    # steps: 
    #  - name: TEST WEBAPI
    #     run: dotnet run

      

