on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v3
      - name: GET DOTNET       
        run: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb  
      - name: INSTALL .NET
        run: sudo dpkg -i packages-microsoft-prod.deb      
      - name: INSTALL SDK
        run: sudo apt-get install -y dotnet-sdk-6.0     
      - name: LIST DOTNET
        run: dotnet --list-sdks
      - name: LIST RUNTIME
        run: dotnet --list-runtimes
      - name: BUILD TEST
        run: dotnet build
      - name: TEST .NET
        run: dotnet test
      - name: RUNNING DOT API
        run: dotnet run

  

      

