on:
 push:
   branches: ["main"]
      
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:  INSTALL .NET SDK6.0      
        uses: actions/checkout@v3
        run: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        run: sudo dpkg -i packages-microsoft-prod.deb
        run: sudo apt-get update &&   sudo apt-get install -y dotnet-sdk-6.0
        run: sudo apt-get install -y aspnetcore-runtime-7.0

    steps: BUILD WEBAPI
       run: dotnet build

    steps: TEST WEBAPI
       run: dotnet test

      

